version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: kennwort1
      MYSQL_DATABASE: diary
      MYSQL_USER: user
      MYSQL_PASSWORD: kennwort1
